trigger:
  - "*"

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: buildDotNet
    displayName: "Build and test dotnet"
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: "build"
        displayName: "Build dotnet"
      - script: "dotnet test"
        displayName: "Run dotnet tests"

  - job: buildNode
    displayName: "Build and test node"
    steps:
      - task: UseNode@1
        inputs:
          version: "20.x"
        displayName: "Set up Node"
      - script: |
          npm ci
          npm run build
          npm run lint
          npm t
        workingDirectory: "DotnetTemplate.Web"
        displayName: "Run npm scripts"

  - job: buildAndPushDocker
    displayName: "Build and push docker image"
    dependsOn: [buildDotNet, buildNode]
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: aleyipDockerHub
          command: buildAndPush
          Dockerfile: "./Dockerfile"
          repository: "aleyipsoftwire/workshop-m9"
          tags: latest
